# This file was generated by GoReleaser. DO NOT EDIT.
cask "filex" do
  version "0.49.0"

  on_macos do
    on_arm do
      sha256 "062445bbc171e07d2505a8ba5b91129be2408f2f21bee642c54fb3f25726c6e8"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f1a293d50fbb0e2e90651600650f8d711c2b793a34b622d230757a4d037dbbc"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1a16b11f17fe68ebc47a264c541116349f72fe19cfc0e09a173deeb039dc5293"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5f34459ac573ba32c5b6045373be738c8c0f74846464beb2429404e1ebd449c"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "filex"
  desc "Self-hosted file manager: server, folder sync and CLI in one binary"
  homepage "https://filex.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filex"

  # No zap stanza required

  caveats <<~EOS
    On macOS: filex is not signed with an Apple Developer ID, so macOS may
    refuse to run it the first time. Allow it once in System Settings →
    Privacy & Security ("Open Anyway"), then run the command again.
  EOS
end
