# This file was generated by GoReleaser. DO NOT EDIT.
cask "filex" do
  version "0.50.0"

  on_macos do
    on_arm do
      sha256 "fe02a9ee9b6a725b0c015e4081cb8b387d9f5593302f6e95089b801a5f7e0f83"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0580b52a6302d3d18f6dd19d272c029d58012328b850e502c8ff83d3c9b8faac"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5198460ead14584875ae0289dbb1200373bca160a23b9a2f67095de327ca7e5"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "960d51aa03d34decdd39e3ec211dd001f4df49aa7908476f92e0ad539006bbf8"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "filex"
  desc "Self-hosted file manager: server, folder sync and CLI in one binary"
  homepage "https://filex.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filex"

  # No zap stanza required

  caveats <<~EOS
    On macOS: filex is not signed with an Apple Developer ID, so macOS may
    refuse to run it the first time. Allow it once in System Settings →
    Privacy & Security ("Open Anyway"), then run the command again.
  EOS
end
