# This file was generated by GoReleaser. DO NOT EDIT.
cask "filex" do
  version "0.44.0"

  on_macos do
    on_arm do
      sha256 "66872d5798070733a045259a9911762b91673bd2a85f28d71ac30699c2316f45"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7bb3ef6cb5b2590c9576cb197b7fbc62ba34833410ab6c4e0b41ad516ae2ca5"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "051df5416d87186fdfb6f5696f74dff0c8cae212bebc8e1f0d4a320037f1dec3"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43393199c12c634b6462ce98acaa993c8cfbd096d5730483a711444af09a24e4"
      url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "filex"
  desc "Self-hosted file manager: server, folder sync and CLI in one binary"
  homepage "https://filex.sh/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filex"

  # No zap stanza required

  caveats <<~EOS
    On macOS: filex is not signed with an Apple Developer ID, so macOS may
    refuse to run it the first time. Allow it once in System Settings →
    Privacy & Security ("Open Anyway"), then run the command again.
  EOS
end
