# Generated by desktop/scripts/pkg-manifests.mjs in github.com/BRF-Tech/filex —
# edit the generator, not this file; the release job overwrites it.
cask "filex-app" do
  version "0.44.2"
  sha256 "0e6442ee92e0530c875fcb622f4fa628a9407bff32a24f977019302877716f11"

  url "https://github.com/BRF-Tech/filex/releases/download/v#{version}/filex-desktop-arm64.dmg"
  name "filex"
  desc "Desktop app for the self-hosted filex file manager"
  homepage "https://filex.sh/"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The macOS build cannot replace itself (it is ad-hoc sealed, not signed with
  # a Developer ID), so `brew upgrade` is what updates it.
  auto_updates false
  depends_on arch: :arm64
  depends_on macos: ">= :ventura"

  app "filex.app"

  # Only the desktop app's own files. ~/.filex is shared with the filex CLI
  # (sync pairs, baselines) and is left alone.
  zap trash: [
    "~/.filex/desktop",
    "~/Library/Application Support/@brftech/filex-desktop",
    "~/Library/Preferences/sh.brf.filex.desktop.plist",
    "~/Library/Saved Application State/sh.brf.filex.desktop.savedState",
  ]

  # No Developer ID (Burak, 2026-09-25): the app is ad-hoc sealed, and Homebrew
  # keeps macOS's quarantine on what a cask downloads, so the first launch is
  # stopped once and the user lets it through. Said here rather than worked
  # around: removing the quarantine for them is exactly what Homebrew declines
  # to make easy.
  caveats <<~EOS
    filex is not signed with an Apple Developer ID, so macOS blocks its first
    launch. Open it once, then go to System Settings → Privacy & Security and
    click "Open Anyway" next to filex.
  EOS
end
